name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo build
      - run: cargo test
      - run: cargo test --features="tokio"
      - run: cargo test --features="async-std"
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --node -- --features="lib-wasm-bindgen"
      - run: cargo test --features="full"
