name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo build
      - run: cargo test
      - run: cargo test --features="lib-tokio"
      - run: cargo test --features="full"
